### ISSUE TITLE
ZDrawer not working with elements that are far from origin

### ISSUE THREAD

**Issue by AitorSimona** [Broken-Gem-Studio/Broken-Engine#102]
## Bug Description
Elements too far from origin do not react to ZDrawer

## Type of Bug 
Select the type of bug with and "x" ([x])

* [X] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [X] Cosmetic 

## Reproduction

 1. Load VS1 level, activate ZDrawer (panelScene - DebugDraw menu)
 
 2. 
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [X] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Proper reaction to ZDrawer

### Actual result:
No reaction, all black

## Build
- **Please specify the build:** ``Insert the build here``
Dev branch commit 1211

**Comment by lucho1** [comment]
Have you tried to modify the camera's far plane?

**Comment by t3m1X** [comment]
If this fixed @AitorSimona? Is so close it, please.

**Comment by AitorSimona** [comment]
Would be closed if it was fixed :)

**Comment by AitorSimona** [comment]
ZDrawer is worth nothing right now, closing this issue.
