### ISSUE TITLE
Memory leak on ModuleRenderer3D

### ISSUE THREAD

**Issue by t3m1X** [Broken-Gem-Studio/Broken-Engine#104]
## Bug Description
ModuleRenderer3D::textShader is not being deleted on CleanUp, creating a memory leak

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [X] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [X] Other

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [X] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

**Comment by lucho1** [comment]
fixed
