### ISSUE TITLE
When putting a GObj as child, this one cannot be reseted to a parent

### ISSUE THREAD

**Issue by lucho1** [Broken-Gem-Studio/Broken-Engine#105]
## Bug Description
If you put a children to a game object, the children cannot be "de-parented"

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [x] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1. Make 2 game objects
 
 2. Put one of them as a child of the other
 
 3. You cannot put the children game object to not to have a parent

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
The child game object can be unparented

### Actual result:
You cannot put the children game object to not to have a parent

## Build
- **Please specify the build:** ``Insert the build here``
v0.3.0

**Comment by AitorSimona** [comment]
Most likely this bug was introduced when implementing ModuleSelection, that heavily changed stuff in the hierarchy. As such, I'm assigning @ponspack9 to it.

**Comment by t3m1X** [comment]
It seems you cannot make a GO a child of anything below itself in the hierarchy, also you need to click it before parenting it, porting this info from my issue.
