### ISSUE TITLE
Buttons don't Save the colors & stop working after pressing "STOP" button

### ISSUE THREAD

**Issue by lucho1** [Broken-Gem-Studio/Broken-Engine#106]
## Bug Description
The button stop working when pressing the stop button of engine's editor, but in addition it seems to not storing the colors setted (for idle, hovering, selected...) after pressing stop button.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [x] Components
* [ ] Game Objects
* [x] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1. Make a Button UI Element 
 
 2. Change the colors (hover, ...) and press play
 
 3. Press stop

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Button should always work and keep the desired colors

### Actual result:
It doesn't

## Build
- **Please specify the build:** ``Insert the build here``
v0.3.0

**Comment by lucho1** [comment]
It seems that happens something similar with bars

**Comment by DavidTello1** [comment]
Colors are now saved in Save&Load
