### ISSUE TITLE
Adding a texture to a .mat (material) of an FBX does not apply the texture to any of the FBXs that use the material

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#109]
## Bug Description
Read Title

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [x] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Drag the Geralt or Sword texture to its correspondent .mat FBX slot.
 
 2. 
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
FBX stops being white and adopts the texture.

### Actual result:
FBX remains white, untextured.

## Screenshots and Illustrations:
![image](https://user-images.githubusercontent.com/36209557/77566354-d175ea80-6ec5-11ea-8db5-b69f09146780.png)

## Build
0.3.0

**Comment by lucho1** [comment]
@ch0m5, I have already noticed this, I think the changes are in development already, so if in the next build (v0.3.1) it works, please, close it :)
