### ISSUE TITLE
Naming game objects with relation to it's "type"

### ISSUE THREAD

**Issue by Xulu-u** [Broken-Gem-Studio/Broken-Engine#111]
## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [x] Game Objects
* [ ] UI/UX
* [ ] Other

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [ ] **Increased Performance**: Optimization which would improve execution performance.
- [ ] **New Feature**: It's an additional feature that fits in the product.
- [ ] **Developer Quality of Life Upgrade**: It would optimize current or new implementations.
- [x] **User Quality of Life Upgrade:** It would improve the User Experience.
- [ ] **Other**: *Describe reason here*

## Implementation Instructions and Guidelines
Example: When I create a "Camera" GO its name is GameObject(xxx). So my proposal is to name it according to it's type, meaning: Creating a camera its name will be Camera(xxx) and so for every type. For imported fbx using it's own name + the number of copies would be nice aswell.

**Comment by DavidTello1** [comment]
solved
