### ISSUE TITLE
GetGameObjectPos() Script returns nil values of a valid UID parameter

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#112]
## Bug Description
GetGameObjectPos() Script returns nil values of a valid UID parameter

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [x] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. 
 
 2. 
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [ ] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Function returns position values

### Actual result:
Function returns nils

## Build
0.3.0

## Observations and Additional Information
The individual GetGameObjectPosX, Y, Z, methods work correctly.

**Comment by DidacRomero** [comment]
Whenever the pull request from the branch of the fix is merged this issue will be closed, te issue is resolved. You receive a table with 3 numbers indexed as 1 (X), 2 (Y), 3(Z), this is done in thsi way since when we pass a value from the function the pushfloats are not working properly.
