### ISSUE TITLE
Generate a console txt file when Broken engine crash

### ISSUE THREAD

**Issue by Jaumeavinyo** [Broken-Gem-Studio/Broken-Engine#115]
## Enhancement Description
A ver, muchas veces, a los programadores de gameplay en lua nos pasa que nos peta el motor porque "Algo salió mal" con el script. Cuando esto pasa no nos da tiempo a ver la consola por si nos diera una informacion util respecto a la razón por la que peta. 
Por esto me gustaria saber si seria posible generar un txt cada vez que se le da al play button con los logs de consola para no perderlos cuando el motor peta

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX
* [x] Other

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [ ] **Increased Performance**: Optimization which would improve execution performance.
- [x] **New Feature**: It's an additional feature that fits in the product.
- [x] **Developer Quality of Life Upgrade**: It would optimize current or new implementations.
- [x] **User Quality of Life Upgrade:** It would improve the User Experience.
- [ ] **Other**: *Describe reason here*

## Implementation Instructions and Guidelines
Como no conozco muy bien como va la consola, para esto deberia hablar con quien quiera o se le asigne la tarea

## Observations and Additional Information
jaume

**Comment by t3m1X** [comment]
There is a LUA debugger now, so this should not be necessary.
