### ISSUE TITLE
Inspector UI only shows 1 script at a time, even when having several

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#12]
## Bug Description
Only 1 script is "allowed" on the Inspector window of a GameObject. Adding a 2nd script on a Game Object seems to override the 1st, but when pressing play the 1st script still runs. I assume that "visually" the 2nd overrides the 1st in the UI, but both are still added as components to the GO.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [x] Components
* [ ] Game Objects
* [x] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Add a script to a GO
 
 2. Add a 2nd, different script to a GO
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
2 script components

### Actual result:
2nd script seems to override the 1st on the UI, but both run when pressing PLAY,  so both are components of the GO, but on the UI only 1 is showed

## Build
https://github.com/Broken-Gem-Studio/The-Witcher-Ties-of-Destiny/tree/9bbc23593b63c623d40539bff32b95687d2d453b

## Observations and Additional Information
There seems to be an issue related to script instances being correctly added to GO but the UI only showing 1 of them: the last added on the Inspector.

**Comment by DidacRomero** [comment]
This issue has been solved recently solving a very similar issue.

This issue will now be closed.
