### ISSUE TITLE
Scene Save/Load doesn't save component active state

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#128]
## Bug Description
When reloading a scene that has GOs with deactivated components, on load they're always set as active.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [x] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Create GO
 
 2. Create components in GO
 
 3. Deactivate components in GO

 4. Play/Stop

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
GO components remain deactivated during and after PLAY

### Actual result:
GO components are set as active after STOP, on Scene Load

## Build
0.3.0

**Comment by JosepLleal** [comment]
This was fixed in issue #68
