### ISSUE TITLE
Adding the same script to a GO multiple times shows it only once in the UI, but runs each one added

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#13]
## Bug Description
Adding the same script to the same GO multiple times adds a new script instance for each time, but only 1 script is shown in the UI. Technically, it should only accept 1 script of the same type/name per GO.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [x] Components
* [ ] Game Objects
* [x] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Add a script to a GO
 
 2. Add the same script to the GO several times
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
The GO only accepts one instance of the same script.

### Actual result:
It accepts several, but only 1 is ever shown in the UI.

## Build
https://github.com/Broken-Gem-Studio/The-Witcher-Ties-of-Destiny/tree/9bbc23593b63c623d40539bff32b95687d2d453b

## Observations and Additional Information
There seems to be an issue related to script instances being correctly added to GO but the UI only showing 1 of them: the last added on the Inspector.

**Comment by DidacRomero** [comment]
This issue has been solved, as of now, script components & audio sources can be added multiple times to a gameobject, allowing it to hold diferent scripts & audio files (soyrces).

This issue will now be closed.
