### ISSUE TITLE
Scene Save/Load seems to ignore various elements from components (QA Task)

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#130]
## Bug Description
Bugs like #128 and #129 lead me to believe that there are many other components or similar Scene elements that are ignored by the Save/Load system. Someone should try different GOs with different components and see what remains intact after a Play/Stop and what uses a default value instead, ignoring the value before Play.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [x] Resource Management & Save/Load 
* [ ] Materials 
* [x] Components
* [x] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Whatever you deem necessary, but it's highly recommended to try out most if not all GO components and check if they load their values correctly.
 
 2. 
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Everything is loaded exactly as it was before Play.

### Actual result:
Some elements are saved, such as GO position, but others such as component active state or collider IsTrigger aren't.

## Build
0.3.0

## Observations and Additional Information
Issues #128 and #129 are specific examples that are part of this problem. Also, this Issue seems to happen with the Save/Load system regardless of the type of loading, be it a Scene saved beforehand (Load Scene DefaultScene for example) or the Temporal Scene (Play/Stop).

**Comment by AitorSimona** [comment]
Both linked issues were closed, closing this one also. If any element is not Save&Loaded, please specify which so the relevant person can be noticed.
