### ISSUE TITLE
Colliders should have an Active/Unactive state to switch through UI, as a component it is

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#133]
## Bug Description
Colliders don't have an Active/Unactive state, as shown in the Inspector UI, they should, as any other component.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [x] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Create a GO
 
 2. Add Collider component
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Collider has Active Checkbox.

### Actual result:
Collider has is a component without a checkbox.

## Build
0.3.0

## Observations and Additional Information
Colliders **are** activated and deactivated following the owner GO, but they have no active state to switch of their own through UI.

**Comment by t3m1X** [comment]
Done in #178
