### ISSUE TITLE
SetActiveGOParticleEmitter(UID, true/false), a scripting method to activate/deactivate a the particle emitter of a GO by UID

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#137]
## Enhancement Description
SetActiveGOParticleEmitter(UID, true/false), a scripting method to activate/deactivate a the particle emitter of a GO by UID.

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [x] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [x] Components
* [ ] Game Objects
* [ ] UI/UX
* [ ] Other

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [ ] **Increased Performance**: Optimization which would improve execution performance.
- [x] **New Feature**: It's an additional feature that fits in the product.
- [ ] **Developer Quality of Life Upgrade**: It would optimize current or new implementations.
- [ ] **User Quality of Life Upgrade:** It would improve the User Experience.
- [ ] **Other**: *Describe reason here*

**Comment by lucho1** [comment]
Aixo es totally necessari?

**Comment by lucho1** [comment]
Just asking, tampoc es tan dificil

**Comment by ch0m5** [comment]
Si, si que ho és. Alternativament necessito que **com a mínim** es pugui activar/desactivar un GO, però poder activar/desactivar el emitter s'utilitzarà molt.
