### ISSUE TITLE
Particle Emitter Rotation + Offset

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#138]
## Enhancement Description
I want to be able to rotate the Particle Emitter so that it can fit Geralt's Sword. I can currently make a "long horizontal line" that emits particles by putting the Particle Emitter Size parameter to 0,0,10, but it's not affected by the GOs rotation. The size always strictly follows the World Axis coordinates and can't be rotated.

Therefore, I need a Rotation editor value for the Particle Emitter that rotates it, making so the "line" previously mentioned gets rotated depending on its value. Alternatively, make the Particle Emitter rotate depending on the GO Rotation value, though the first option is ideal.

Also, having an Offset value such as the component Collider does would also help, making the Particle Emitter be able to have its position changed without having to change the position of the GO. However, if this wasn't implemented, we could have empty GO that only held the Particle Emitter and use the GO's position, but having an Offset would help and give more flexibility.

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [x] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX
* [x] Other

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [ ] **Increased Performance**: Optimization which would improve execution performance.
- [x] **New Feature**: It's an additional feature that fits in the product.
- [ ] **Developer Quality of Life Upgrade**: It would optimize current or new implementations.
- [ ] **User Quality of Life Upgrade:** It would improve the User Experience.
- [ ] **Other**: *Describe reason here*

**Comment by X0KA** [comment]
Features implemented. Need testing
