### ISSUE TITLE
.gitignore not fully functional (The Witcher Repository)

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#142]
## Enhancement Description
I see .meta files being uploaded to GitHub, and as I understand it they are not necessary, just like the Library files. Maybe I'm wrong, but if not the .gitignore for The Witcher Builds repository should be updated to avoid eventually overloading the repository.

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX
* [x] Other

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [x] **Increased Performance**: Optimization which would improve execution performance.
- [ ] **New Feature**: It's an additional feature that fits in the product.
- [ ] **Developer Quality of Life Upgrade**: It would optimize current or new implementations.
- [ ] **User Quality of Life Upgrade:** It would improve the User Experience.
- [ ] **Other**: *Describe reason here*

**Comment by lucho1** [comment]
Please, Issues regarding the game's repo, put them in the game's repo
