### ISSUE TITLE
Differentiate between "shared" variables and "editor" variables

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#149]
## Enhancement Description
Currently every script uses "lua.table" as a way to both show variables in the engine Inspector and to make them accessible from other scripts. This has resulted in tons of variables that will never be changed in the Inspector nor have any need to, yet are shown because they form part of the lua_table.

There need to be 2 classifications: values shown in the Inspector and values that are open to be shared with other scripts. Using a single table for both results in the Editor Inspector being almost completely useless for scripting purposes.

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [x] Components
* [ ] Game Objects
* [ ] UI/UX
* [ ] Other

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [ ] **Increased Performance**: Optimization which would improve execution performance.
- [ ] **New Feature**: It's an additional feature that fits in the product.
- [x] **Developer Quality of Life Upgrade**: It would optimize current or new implementations.
- [ ] **User Quality of Life Upgrade:** It would improve the User Experience.
- [ ] **Other**: *Describe reason here*

**Comment by t3m1X** [comment]
Closed by #282
