### ISSUE TITLE
Hot Reloading not working

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#15]
## Bug Description
Changing a script directly on a file and saving it does not reload the script on the engine, so the "previous" unchanged version of the script is used instead of the new edited one. You must restart the engine for the script to reload.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [x] Resource Management & Save/Load 
* [ ] Materials 
* [x] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Assign a script to a GO
 
 2. Run script
 
 3. Change script file separately through an IDE (like VS) and save it

 4. Run script again

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Script runs differently according to the new changes made and saved through the IDE.

### Actual result:
Script runs exactly as before the changes, as it didn't update.

## Build
https://github.com/Broken-Gem-Studio/The-Witcher-Ties-of-Destiny/tree/9bbc23593b63c623d40539bff32b95687d2d453b

**Comment by DidacRomero** [comment]
Current Issue is listed as an improvement. Component script variables don't take into account if its variables are deleted or commented on hot reloading.
