### ISSUE TITLE
A lot of ScriptingFunctions that use lua_State* are badly implemented

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#154]
## Bug Description
A lot of ScriptingFunctions that use lua_State* are badly implemented. lua_State must be the last parameter ALWAYS and when using lua_pushnumber() the return value of the function must be the amount of lua_pushnumbers() made within the function.

Check the documentation and take a look to GetLinearVelocity() scripting method, which uses lua_State and has worked since its first implementation.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [x] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. 
 
 2. 
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

## Build
0.3.1

**Comment by t3m1X** [comment]
Fixed this #170
