### ISSUE TITLE
MeshRenderer is not being saved (Sometimes)

### ISSUE THREAD

**Issue by t3m1X** [Broken-Gem-Studio/Broken-Engine#159]
## Bug Description
When saving a scene the mesh renderers components are not being saved thus the meshes are not rendered

## Type of Bug 
Select the type of bug with and "x" ([x])

* [X] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [X] Components
* [X] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [X] Cosmetic 

## Reproduction

 1. Save a scene
 
 2. Load a scene
 
 3. Magic

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [ ] Always
* [ ] Very Often
* [ ] Usually
* [X] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Meshes should be seen

### Actual result:
Invisible Geralt!

## Build
- **Please specify the build:** ``Insert the build here``
All

## Observations and Additional Information
Pls fix this

**Comment by AitorSimona** [comment]
Could not reproduce, any more info on this? @t3m1X

**Comment by t3m1X** [comment]
> 
> 
> Could not reproduce, any more info on this? @t3m1X

I personally could not replicate, might have been related to another underlying issue

**Comment by t3m1X** [comment]
Will be reopened if issue resurfaces
