### ISSUE TITLE
Culling Camera in Camera Component not working

### ISSUE THREAD

**Issue by lucho1** [Broken-Gem-Studio/Broken-Engine#18]
## Bug Description
Marking a camera component as current culling camera doesn't make it to be (at least visually) the current culling camera.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [x] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1. Make a camera
 
 2. Mark, in the component camera, the checkbox of "Current Culling Camera"
 
 3. Move the camera with some objects in the scene and see it's not working

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
To cull objects outside camera frustum

### Actual result:
Doesn't cull them

## Build
- **Please specify the build:** ``Insert the build here``
The current development branch

**Comment by X0KA** [comment]
Issue solved. Merge done

**Comment by lucho1** [comment]
For the next issues, once done, close it directly please
