### ISSUE TITLE
UI Render Order Not Working

### ISSUE THREAD

**Issue by lucho1** [Broken-Gem-Studio/Broken-Engine#181]
## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. 
 
 2. 
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [ ] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

## Build
- **Please specify the build:** ``Insert the build here``

**Comment by t3m1X** [comment]
This should be working with GO ordering now working when saving/loading? #173 @lucho1

**Comment by lucho1** [comment]
@DavidTello1 solved this and it's on development now
