### ISSUE TITLE
Scene Unloading seems to Crash

### ISSUE THREAD

**Issue by lucho1** [Broken-Gem-Studio/Broken-Engine#182]
## Bug Description
Something related to scripting deletion, when you sometimes unload a scene, engine crashes.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [x] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [x] Crash 
- [ ] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Load VS3
 
 2. Try to go from Cinematic to Game Scene
 
 3. :')) 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [ ] Always
* [x] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
New Scene Should be loaded

### Actual result:
Crash

## Build
- **Please specify the build:** ``Insert the build here``
v0.3.9.5

**Comment by t3m1X** [comment]
Probably has to do with loading a scene with fewer scripts than you have in the current scene.

**Comment by DidacRomero** [comment]
This issue has been solved in the current pull request Scripting, this issue will be closed automatically when the pull request is accepted. Thank you @t3m1X @lucho1
