### ISSUE TITLE
"Stop" game doesn't restart the scripts (nor the scene)

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#19]
## Bug Description
Stopping the Game Mode of the engine "pauses" it, it doesn't stop it, as there is not scene previous state reloaded nor the script variables are reset the their original values.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [x] Resource Management & Save/Load 
* [ ] Materials 
* [x] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Put a script into a GO
 
 2. Play game
 
 3. Stop game

 4. Play game

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
All script vars should reset when stopping the game and the scene state previous to PLAY should reload. Both Awake and Start should play when starting the script for the first time, Awake only once per script, Start every time that the component is enabled.

### Actual result:
Nothing reloads, STOP works as a PAUSE.

## Build
https://github.com/Broken-Gem-Studio/The-Witcher-Ties-of-Destiny/tree/408d0a7c98d196cb743cdcd52340f22de0bcd3b1

**Comment by DidacRomero** [comment]
Hi @ch0m5 I understand you only take into account Awake & start functions as well as variables of the table class. If you do not refer to the local vars that don't belong to the table then this issue has been solved in a past build and will be closed.

**Comment by ch0m5** [comment]
> 
> 
> Hi @ch0m5 I understand you only take into account Awake & start functions as well as variables of the table class. If you do not refer to the local vars that don't belong to the table then this issue has been solved in a past build and will be closed.

Correct. My main evaluation method of assuming it wasn't reset correctly is not seeing the Awake and Start methods being played again after restarting the scene. I would very much appreciate if you could test if activating and deactivating a script plays the Start() method on reactivation. If you want further information or testing feel free to contact me.

**Comment by DidacRomero** [comment]
Thank you @ch0m5 , this issue was resolved a few days after you posted the issue, but took a little bit more time to merge, this issue will now be closed.
