### ISSUE TITLE
Baker House FBX seems to work incorrectly

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#20]
## Bug Description
Dragging the .FBX file from resources to the scene creates a GO which holds all his parts as children GO. The father GO has its number value assigned as 0, ignoring the engine GO counter when assigning the name. Also, the mesh instantly disappears when dragging it to scene.

**THIS BUG ONLY HAPPENS WITH BAKER HOUSE**. But this happening is concerning and could be a warning flag of an error.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [x] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Drag .FBX file from Project to Scene 2 or more times
 
 2. 
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
The created GOs have different names.

### Actual result:
The created GOs have the same name.

## Screenshots and Illustrations:
![image](https://user-images.githubusercontent.com/36209557/75568907-6c5cdf80-5a54-11ea-8b2f-ab145b71b6b1.png)

## Build
https://github.com/Broken-Gem-Studio/The-Witcher-Ties-of-Destiny/tree/a0a24b7b32046e03e4d589270ab3bf1a7f525103

## Observations and Additional Information
The counter is used when creating the GOs, but not applying it correctly to the name's string. As you can see in the screenshot, the last 2 GOs, which were created using the default 3D Objects from the engine have their suffix applied correctly according to the engine GO counter.

**Comment by AitorSimona** [comment]
baker house appears on the scene (turn around the camera), the name is correctly set, when the engine imports it assigns a new name taking into account the go_count, but when you instance on scene it just loads the name written into the .model file, whether it is GameObject(0) or Goose
