### ISSUE TITLE
Name for Materials

### ISSUE THREAD

**Issue by Jaumeavinyo** [Broken-Gem-Studio/Broken-Engine#209]
## Enhancement Description
I'd like to be able to give names to newly created materials

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [x] Visual 
* [x] UI/UX

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [x] **Developer Quality of Life Upgrade**: It would optimize current or new implementations.
- [x] **User Quality of Life Upgrade:** It would improve the User Experience.

## Implementation Instructions and Guidelines
be able to put a name as with other game objects

## Observations and Additional Information
jaume

**Comment by lucho1** [comment]
Duplicated by #75
