### ISSUE TITLE
See selected objects as highlighted objects in the scene

### ISSUE THREAD

**Issue by Jaumeavinyo** [Broken-Gem-Studio/Broken-Engine#210]
## Enhancement Description
make selected objects be more visible in the scene

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [x] Visual 

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [x] **Developer Quality of Life Upgrade**: It would optimize current or new implementations.

## Implementation Instructions and Guidelines
just hightlight the selected objects, don't really care the color o style, just want to be able to identify selected objects

## Observations and Additional Information
jaume

**Comment by t3m1X** [comment]
Solved on commit d8e5222
