### ISSUE TITLE
Need  different blends for different animations

### ISSUE THREAD

**Issue by Jaumeavinyo** [Broken-Gem-Studio/Broken-Engine#215]
## Enhancement Description
Ahora mismo el blend funciona igual para todas las animaciones, no es que me vaya la vida en ello pero queda muy mal visualmente porque tengo animaciones que necesitan empezar sin ningun blend y otras que si, asi que necesito que al hacer un play animation, el anim system mire que blend time tiene la proxima animacion y lo aplique. Así cada anim tendra su propio blend time para empezar.

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [x] Visual 
* [x] Game Objects
* [x] Other

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [ ] **Increased Performance**: Optimization which would improve execution performance.
- [x] **New Feature**: It's an additional feature that fits in the product.
- [x] **Developer Quality of Life Upgrade**: It would optimize current or new implementations.
- [x] **User Quality of Life Upgrade:** It would improve the User Experience.
- [x] **Other**: *Describe reason here*
Aclaro que no es algo que me apetezca hacer, es que sino hay anims que me quedan fatal
## Implementation Instructions and Guidelines
Hablar con Jaume de Design

**Comment by ch0m5** [comment]
Visto que ha pasado un mes supongo que esto ya esta solucionado, pero puedes llamar a SetBendTime en el mismo frame que se hace el Play() de la animation y usará ese BlendTime. eso debería resolver tu problema.

**Comment by lucho1** [comment]
Jaume, tancaré aquesta issue precisament pel que comenta en @ch0m5 ... De fet, t'explico: Hem mirat de fer-ho de manera q es pugui fer com vas demanar (canviant-ho desde el component), pero això requeriría tocar el save/load del recurs d'animació ja que s'hauria de guardar, en el recurs, aquest blend time per a cada animació que tinguis... Fer això implicaría recarregar tant l'escena com la library (és a dir, tornar a fer i carregar l'escena i totes les animacions), cosa que a aquestes alçades no es pot fer, sorry :(

Tot i així, el que comenta en @ch0m5, es una manera de fer-ho, així que ho pots fer com diu ell, que a efectes pràctics i visuals és el mateix.

**Comment by lucho1** [comment]
Al final he descobert una manera de fer-ho sense petar l'escena. Si la pull #365 s'accepta, estarà a dev i a la proxima build (he fet una checkbox per seguir utilitzant el default blend time com es feia fins ara en cas que no ho volgueu canviar!)
