### ISSUE TITLE
Scripting Function "RotateObject" works as a SetRotation

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#232]
## Bug Description
RotateObject does not rotate the object by the required degrees, and instead just sets the rotation to the same global direction no matter the current Rotation of the GO's transform.

This was tested with a GO that uses a CharacterController component.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. 
 
 2. 
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [ ] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

## Build
- **Please specify the build:** ``Insert the build here``

**Comment by t3m1X** [comment]
This is indeed true, thanks for the heads-up, getting on fixing it
