### ISSUE TITLE
Wireframe Collisions can not be seen

### ISSUE THREAD

**Issue by TheArzhel** [Broken-Gem-Studio/Broken-Engine#235]
## Bug Description
When setting the collisions, adding box colliders and deactivating the mesh renderer, we ca not see the bow wireframe as before. version 0.4.2.6

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1.  load mesh collider
 
 2.  add collider box
 
 3. deactivate the mesh renderer

 4. cannot see the box if it is not clicked

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
when addind a box collider, i can see the wireframe of the object

### Actual result:
when adding a box collider i dont see any changes

## Build
- **Please specify the build:** ``Insert the build here``
0.4.2.6

## Observations and Additional Information
-cualquier cosa preguntar a andres

**Comment by t3m1X** [comment]
You need to click on the "Show" button in the component mesh collider.
