### ISSUE TITLE
Engine Does not open after saving

### ISSUE THREAD

**Issue by TheArzhel** [Broken-Gem-Studio/Broken-Engine#236]
## Bug Description
SUMMERY: The engine opens well the firts time I open it, but after creating a Scene and saving its content it crashes.

The second time i try to open the engine, it take a time loading and then crashes. The scen contains materials, gameobjects, scripts. At the time it happens with 1 or 2 scenes, i havent try with more scenes. gameobjects may contain several components.

There is then no way (that i have found) to get the scene back, i have to start all over again.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [x] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [x] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [x] Crash 
- [ ] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Open carles scene 0.4.2.6. Add blockout and collision. Add scripts to characters
 
 2. Add: blockout and collision, scripts to characters
 
 3. Import new assetes needed. 

 4. OPTIONAL Create a new Scene with gameobjects

5. Save and close the engine

6. Try opening again.

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [ ] Always
* [x] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
open the engine without problem a second time after saving

### Actual result:
cannot open the engine a econd time

## Build
- **Please specify the build:** ``Insert the build here``
0.4.2.6

## Observations and Additional Information
Preguntar a andres cualquier pregunta

**Comment by t3m1X** [comment]
Closing because we could not replicate, stale.
