### ISSUE TITLE
Scne tab does not show anything after fullscreen

### ISSUE THREAD

**Issue by TheArzhel** [Broken-Gem-Studio/Broken-Engine#237]
## Bug Description
i open the engine and afer making the engine app hole screen, it does not show anything in the scen tab (only the gizmo with color)

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [x] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. open the engine
 
 2. make it hole screen
 
 3. encounter black screen of death

 4. cry

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [ ] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [x] Few Times under specific conditions

### Expected result:
have a engine with holescreen and seeing the scene and meshes

### Actual result:
have a blackscreen where you cannot see anything in the scene tab

## Screenshots and Illustrations:
attach

## Build
- **Please specify the build:** ``Insert the build here``
0.4.2.6

## Observations and Additional Information
andres saladrigas
![black screen of death](https://user-images.githubusercontent.com/36264953/79639959-2f2ce800-818f-11ea-975e-2fa0b18136f0.PNG)

**Comment by t3m1X** [comment]
Could not replicate this issue.

**Comment by lucho1** [comment]
I have made the step 4 several times already

**Comment by lucho1** [comment]
However, I couldn't made the 3 yet :(

**Comment by t3m1X** [comment]
Closing stale issue.
