### ISSUE TITLE
The "Step" Button does nothing

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#243]
## Bug Description
Read Title.

The behavior expected would be the same for Unity:
- If the game is stopped, pressing Step would be equal to pressing Play but pausing after the 1st frame.
- If the game is playing and Step is pressed, the game is immediately paused.
- If the game is paused and Step is pressed, the game plays for one frame.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [x] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. 
 
 2. 
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

## Build
- **Please specify the build:** ``Insert the build here``

**Comment by AitorSimona** [comment]
Talked to Carles a while back, since no one is expecting this to be fixed and it may take more time than initially thought, as well as impact other areas of the code, I am hereby closing this issue.
