### ISSUE TITLE
"Transparencies" Bool on UI from Material Inspector doesn't work

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#263]
## Bug Description
Either the Bool checkbox does nothing, or most probably the feature doesn't work. There's a GO (Geralt_Slash) which has transparency, but when rendered in front of Geralt, he is not rendered behind it (disappears from the waist and below). When marked the "Transparencies" bool on the checkbox to fix this, nothing changes.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [x] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Scripting
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Use the Geralt_Slash FBX and create one animation in it that goes from 400 to 800, looping to true. Add the Geralt_Slash.png as the Albedo of the material inside Slash_Mesh (or whaterver_Mesh).
 
 2. Put a GO cube behind the Geralt_Slash (so that the slash is in front from the camera's perspective).
 
 3. Make Geralt_Slash a child of the GO cube.

 4. Play and "showcase animation" on the Geralt_Slash only animation.

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
GO is seen through Geralt_Slash in the transparent bits of the Geralt_Slash GO.

### Actual result:
GO is not seen thorugh Geralt_Slash.

## Screenshots and Illustrations:
![image](https://user-images.githubusercontent.com/36209557/79916117-7681d580-8428-11ea-935f-07cf81a73312.png)

## Build
0.4.3

**Comment by lucho1** [comment]
Yup, actually this has been tested... The bool works, however, there is no draw order for materials with partial transparencies, which means that they won't work... We will have to do that :)

**Comment by t3m1X** [comment]
AFAIK This is already done and dusted
