### ISSUE TITLE
Materials Preview Show the Last Preview Created & Move Camera

### ISSUE THREAD

**Issue by lucho1** [Broken-Gem-Studio/Broken-Engine#270]
## Bug Description
The previews of the materials in the Panel Project only show the last preview created.

The camera sometimes is moved when editing a material (probably because of the preview creation?)

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [x] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Scripting
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1. Create more than one materials and see the previews in Panel Project
 
 2. Also, when editing materials, the camera sometimes is moved
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [x] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Preview should show the very own material preview and the materials edition shouldn't move the camera

### Actual result:
Preview show the last preview created and the materials edition sometimes move the camera

## Build
- **Please specify the build:** ``Insert the build here``
v0.4.3.4

**Comment by AitorSimona** [comment]
Tried to create multiple materials, drop textures, unuse them. Tried it on resource inspector node and on mesh renderer material node. Could not reproduce :(

**Comment by lucho1** [comment]
I think that mostly happens in the scene (I don't know if it has something to do with distances or materials quantity?)

**Comment by lucho1** [comment]
Maybe doing the "screenshot" with multithreading fixes it (yup, I'm actually a bit annoying with multithreading, but is not crazy)
