### ISSUE TITLE
Killing Enemies Crashes (only in Build)

### ISSUE THREAD

**Issue by lucho1** [Broken-Gem-Studio/Broken-Engine#272]
## Bug Description
If you kill an enemy in the engine, all goes ok, but killing it in the build sometimes crashes the build.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [x] Game Objects
* [ ] UI/UX 
* [ ] Scripting
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [x] Crash 
- [ ] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Run one of the build scenes
 
 2. Kill enemies in engine
 
 3. Kill enemies in game build

 4. 🗡️ 👯 :D

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [ ] Always
* [x] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Shouldn't crash

### Actual result:
Coffin Meme

## Build
- **Please specify the build:** ``Insert the build here``
v0.4.3.4

**Comment by DidacRomero** [comment]
This issue has been solved, This issue will now be closed.
