### ISSUE TITLE
Audio doesn't changes between Scenes

### ISSUE THREAD

**Issue by lucho1** [Broken-Gem-Studio/Broken-Engine#273]
## Bug Description
The audio isn't changing between Scenes changes

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [x] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Scripting
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1. Load the game build scenes in the engine
 
 2. Run and go through scenes
 
 3. Hear the audio :D

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Audio should work between scenes

### Actual result:
Audio has a weird behaviour

## Build
- **Please specify the build:** ``Insert the build here``
v0.4.3.4

**Comment by sherzock** [comment]
Now We just stop all the audio whenever we change scenes
