### ISSUE TITLE
Audio SetVolume() functions not Working

### ISSUE THREAD

**Issue by lucho1** [Broken-Gem-Studio/Broken-Engine#275]
## Bug Description
Audio, when game is started, is very loud, and it seems that the SetVolume() functions are not 
working

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [x] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Scripting
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1. Load the scene of the last game build in the engine
 
 2. Try to play with the SetVolume() functions, they don't work
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
SetVolume() should modify volume

### Actual result:
SetVolume() doesn't modifies volume

## Build
- **Please specify the build:** ``Insert the build here``
v0.4.3.4

**Comment by sherzock** [comment]
Bug solved
