### ISSUE TITLE
Adding a collider to a scaled object will scale the collider even further

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#28]
## Bug Description
Adding a collider after scaling it seems to scale it again with the same value as the current GOs scale. Ex: A Collider added to a GO of scale 5, will be scaled another 5 units, duplicating the scale of the orig GO. This effect seems to be permanent, changing the scale of the orig GO won't change this difference ratio between GO and Collider once this bug happens.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [x] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [x] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Add GO to scene
 
 2. Scale GO further than 1
 
 3. Add Collider

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Collider is either a default size or is scaled according to the GO correctly.

### Actual result:
Collider is scaled on top of the GO's scale, making it inaccurate to the GO's size.

## Screenshots and Illustrations:
![image](https://user-images.githubusercontent.com/36209557/75862670-966d2380-5dff-11ea-842b-92ed3d5d95cb.png)

## Build
BrokenEngine_v0.1.7

## Observations and Additional Information
The escalation seems to be exactly the same as the one on the GO at the time of the Collider creation. As you can see in the sample image, a Collider created on an object scaled to 5, and then the GO reduced to 1 has the same size as the same GO scaled to 5. Therefore, we can assume that the Collider on a GO of scale 5 was scaled to 5 **again**, on top of the original GO scale value.

**Comment by knela96** [comment]
Fixed on the last version on release
