### ISSUE TITLE
PlayAudioEvent() should have an additional "loop" boolean parameter

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#294]
## Enhancement Description
See Title. Having the option of using an audio event on loop until told to Stop().

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [x] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX
* [ ] Other

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [ ] **Increased Performance**: Optimization which would improve execution performance.
- [x] **New Feature**: It's an additional feature that fits in the product.
- [ ] **Developer Quality of Life Upgrade**: It would optimize current or new implementations.
- [ ] **User Quality of Life Upgrade:** It would improve the User Experience.
- [ ] **Other**: *Describe reason here*

## Implementation Instructions and Guidelines
The idea is to be able to play Walk/Run audio sound only once and have it play until it goes back to idle.

## Observations and Additional Information
**Alternative:** Instead of a loop bool, have an int parameter which marks if it's a loop, has to play once, or x times.

**Comment by lucho1** [comment]
This is done through Wwise as Jacobo said, so I'll close this issue since I understand is something that should not be actually controlled from programming
