### ISSUE TITLE
NavMesh Crash

### ISSUE THREAD

**Issue by knela96** [Broken-Gem-Studio/Broken-Engine#300]
## Bug Description
Sometimes when doing a LoadScene/Load it crashes the build/engine when creating the Navmesh. In the case of a gameplay loop it should be fixed to avoid the crash.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [X] Resource Management & Save/Load 
* [ ] Materials 
* [X] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Scripting
* [X] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [X] Crash 
- [ ] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Play and Stop the game
 
 2. Sometimes it crashes
 
## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [ ] Always
* [X] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

## Screenshots and Illustrations:
![](https://i.imgur.com/q797G1J.png)

## Build
- **Please specify the build:** ``0.5.2``

## Observations and Additional Information
I've tested it with development branch and it crashes the same way

**Comment by t3m1X** [comment]
Fixed by #362
