### ISSUE TITLE
Creating a material closes the engine

### ISSUE THREAD

**Issue by TheArzhel** [Broken-Gem-Studio/Broken-Engine#303]
## Bug Description
Sometimes, Creating a material crashes and closes the engine

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [x] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Scripting
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [x] Crash 
- [ ] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. open the engine
 
 2. load a scene
 
 3. open a assets folder 

 4.  cretae a material

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [ ] Always
* [ ] Very Often
* [x] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
create a material and continue working

### Actual result:
create a material and the engine crashes

## Build
- **Please specify the build:** ``Insert the build here``
0.5.3

## Observations and Additional Information
adrian font knows about this

**Comment by AitorSimona** [comment]
Created and destroyed materials many times and could not reproduce this.

**Comment by lucho1** [comment]
Closed since it get a bit old this issue

**Comment by lucho1** [comment]
And no one could reproduce it
