### ISSUE TITLE
When the engine crashes some GameObjects are deactivated

### ISSUE THREAD

**Issue by DLorenzoLaguno17** [Broken-Gem-Studio/Broken-Engine#309]
## Bug Description
Sometimes when the engine crahses and I reopen it the most of the scene has been deactivates, normally everything except the last GameObject I was editing

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [X] Game Objects
* [ ] UI/UX 
* [ ] Scripting
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [X] Cosmetic 

## Reproduction
I don't know how to reproduce it, because it only happens sometimes and it's very random

 1. 
 
 2. 
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [ ] Always
* [ ] Very Often
* [X] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
I was expecting that when I reopened the engine the scene would load normally 

### Actual result:
The scene load with no problem but almost every gameobject was unactive

## Build
- **Please specify the build:** ``0.5.3``

**Comment by lucho1** [comment]
Just gonna close it since it can't be reproduced or it's not worth
