### ISSUE TITLE
Game State "Save&Load" needs to be separated from regular Saving

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#31]
## Enhancement Description
Playing the current scene should save on a temporal default scene, but this shouldn't be the same as the scene saved manually by the user. In other words: pressing "Play" should **never** overwrite the save file manually created by the user. A testing environment should be facilitated to experiment and iterate without permanent effects on the save file without an explicit order from the user.

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [x] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX
* [ ] Other

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [ ] **Increased Performance**: Optimization which would improve execution performance.
- [x] **New Feature**: It's an additional feature that fits in the product.
- [ ] **Developer Quality of Life Upgrade**: It would optimize current or new implementations.
- [x] **User Quality of Life Upgrade:** It would improve the User Experience.
- [ ] **Other**: *Describe reason here*

**Comment by AitorSimona** [comment]
Done, initial tests show no problem. Engine creates temporal files to store current situation, then loads on stop without touching user's scene
