### ISSUE TITLE
Framerate Decreases on Enemy Deletion

### ISSUE THREAD

**Issue by lucho1** [Broken-Gem-Studio/Broken-Engine#318]
## Bug Description
Each Time an Enemy is Deleted, during a few miliseconds, the framerate decreases. It's not enough to make the game go slower, but it's enough to be notticed

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [x] Game Objects
* [ ] UI/UX 
* [ ] Scripting
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Load a game scene with enemies
 
 2. Play around, find an enemy and kill him while looking at the framerate
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Framerate should not decrease a lot (or at least should not be notticed)

### Actual result:
Framerate decreases

## Build
- **Please specify the build:** ``Insert the build here``
v0.5.4

**Comment by lucho1** [comment]
@t3m1X should be this fixed with multithreading?

**Comment by AitorSimona** [comment]
Problem comes when the last enemy of each type is killed. Discovered that it is produced because of resource unloading. Solution: have an instance of each type deactivated on the map, so resources are never unloaded :)
