### ISSUE TITLE
Create Scripting method to change animation velocity of desired animation.

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#33]
## Enhancement Description
Create Scripting method to change animation velocity of desired animation. Mainly to change the movement animation speed depending on the amount of input from the joystick during play. Being able to choose the target animation would be ideal, changing the currently playing one would be on if its possible uses, and doing so should be possible (no crash).

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [x] Components
* [ ] Game Objects
* [ ] UI/UX
* [x] Other

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [ ] **Increased Performance**: Optimization which would improve execution performance.
- [x] **New Feature**: It's an additional feature that fits in the product.
- [ ] **Developer Quality of Life Upgrade**: It would optimize current or new implementations.
- [ ] **User Quality of Life Upgrade:** It would improve the User Experience.
- [ ] **Other**: *Describe reason here*

**Comment by lucho1** [comment]
I think there is a function in the animations that can do this, like a kind of "SetAnimationSpeed()" or similar... Then, to solve this issue, it would be as easy as to link the scripting system with that function. Talk to @JosepLleal

**Comment by lucho1** [comment]
Donette, habría que testearlo
