### ISSUE TITLE
Changing color of ambient light

### ISSUE THREAD

**Issue by JoanBarduena** [Broken-Gem-Studio/Broken-Engine#332]
## Bug Description
The engine crashes when changing the ambient color on the Rendering Window. 
Changing the palette color with the mouse do not crash the game. Only typing a desired color. 

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Scripting
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [x] Crash 
- [ ] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Open the Ambient color on the Rendering Window. 
 
 2. Changing the color by changing the numbers (rgba, # or hsva).
 
 3. Game crashes. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Change the color to the desired one. 

### Actual result:
Game crashes or not being able to select the color perfectly. 

## Screenshots and Illustrations:
![Bugg](https://user-images.githubusercontent.com/36154195/81188569-c2e71c80-8fb5-11ea-9041-a15425d265b3.png)

## Build
- **Please specify the build:** ``Insert the build here``

**Comment by lucho1** [comment]
Couldn't reproduce in last build... Is this the expected behaviour? 
![GIF](https://user-images.githubusercontent.com/11302677/81502057-eecb1080-92db-11ea-958e-9d1634479215.gif)
