### ISSUE TITLE
Scripting: Setting Time Scale via Scripting

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#348]
## Enhancement Description
Read Title. Being able to change the "background" Time Scale via Scripting for slow-mo effects, fastforward, and other similar time tricks.

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX
* [x] Other

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [ ] **Increased Performance**: Optimization which would improve execution performance.
- [x] **New Feature**: It's an additional feature that fits in the product.
- [ ] **Developer Quality of Life Upgrade**: It would optimize current or new implementations.
- [ ] **User Quality of Life Upgrade:** It would improve the User Experience.
- [ ] **Other**: *Describe reason here*

## Implementation Instructions and Guidelines
A function to change TimeScale, probably located in the System Namespace.

**Comment by AitorSimona** [comment]
Talked to Carles, we concluded that this is not going to be used. I am hereby discarding the feature and closing this issue.
