### ISSUE TITLE
Can't delete a component from an object

### ISSUE THREAD

**Issue by Jaumeavinyo** [Broken-Gem-Studio/Broken-Engine#35]
## Enhancement Description
Unable to delete components from objects.
Being able to Delete Components from the editor would bring a needed QoL change for users of the Engine

We should be able to store them somewhere and load them directly into a new animation.

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [x] Components
* [x] Game Objects
* [ ] UI/UX
* [ ] Other

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [ ] **Increased Performance**: Optimization which would improve execution performance.
- [ ] **New Feature**: It's an additional feature that fits in the product.
- [x] **Developer Quality of Life Upgrade**: It would optimize current or new implementations.
- [ ] **User Quality of Life Upgrade:** It would improve the User Experience.
- [ ] **Other**: *Describe reason here*

## Implementation Instructions and Guidelines
Button to delete components in the node of the component. 
Add a window to confirm the deletion of the Component, in case you click it by mistake.

**Comment by t3m1X** [comment]
Implemented with pull #53, should come out with next release of the engine.
