### ISSUE TITLE
Random Crashes on debug compiling because of Wwise

### ISSUE THREAD

**Issue by AitorSimona** [Broken-Gem-Studio/Broken-Engine#36]
## Bug Description
As the title states, the engine keeps crashing when trying to run, randomly. mmgr exceptions line 1152 mmgr.cpp. 

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [X] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [X] Crash 
- [X] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Just run in debug, you may get it 5 times in a row, once every some time, totally random.
 
 2. 
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [ ] Always
* [X] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
The engine runs without problems...

### Actual result:
The engine keeps crashing randomly and wastes my time

## Screenshots and Illustrations:

![exception](https://user-images.githubusercontent.com/36265599/76086394-4aafab00-5fb4-11ea-8642-c346c049e01f.png)

## Build
- **Please specify the build:** ``Insert the build here``
Latest commit 943, in Release branch

## Observations and Additional Information
No one is taking care of this, since it is on debug. I think it is about time we solve Wwise problems, this is getting ridiculous.

**Comment by t3m1X** [comment]
If this is fixed @sherzock now, please close it.

**Comment by t3m1X** [comment]
Stale issue, closing it
