### ISSUE TITLE
PlayParticleEmitter Delay

### ISSUE THREAD

**Issue by JosepLleal** [Broken-Gem-Studio/Broken-Engine#366]
## Bug Description
After calling the function to play a particle emitter the actual particle starts with a delay of a couple of seconds.

## Type of Bug 
* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [x] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Scripting
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Call the function to play a particle emitter
 
 2. 
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Particle starts instantly

### Actual result:
Particle starts after some seconds

## Build
- **Please specify the build:** ``0.6.1``

**Comment by lucho1** [comment]
Solved by pull #375
