### ISSUE TITLE
SetAnimationPause() pauses different GO's of an FBX at different times

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#371]
## Bug Description
Calling SetAnimationPause() on a GO with animations makes the parent stop faster the the children, which effectively results in Geralt's body freezing on the spot but the sword stopping "later" and therefore remain motionless while floating in the air, away from the hand that's supposed to hold it.

Check Observations below.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [x] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Scripting
* [x] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Use the SetAnimationPause(true) on a scripting function with many layers of children, ideally an FBX such as Geralt or Jaskier.
 
 2. Feel free to contact @ch0m5 to get a Scene Setup to test this.
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
All GOs freeze at the same time.

### Actual result:
Child GOs freeze with a small delay.

## Screenshots and Illustrations:
On freeze point:
TimeScale == 1.0
![geralt_2](https://user-images.githubusercontent.com/36209557/82838045-3603f480-9ecb-11ea-8797-6ef76a0f9894.png)
TimeScale == 0.1
![geralt_1](https://user-images.githubusercontent.com/36209557/82838052-3ef4c600-9ecb-11ea-9b70-4d6a1fe6abee.png)

## Build
0.6.2

## Observations and Additional Information
There seems to be a direct correlation between the engine's execution speed and this bug, since running the game on a very low scale such as 0.1 makes the bug almost imperceptible, probably because the engine is running x10 times faster compared to GameTime and so the timeframe to stop all GOs related to the FBX GO is much higher while the animation is playing much slower. When playing in real time (TimeScale of 1.0) GameTime runs as fast as EngineTime, and the bug occurs as there's a delay between the parent GO pause and the child GOs pause.

You can observe this occurrence in Screenshots.

**Comment by Scarzard** [comment]
Tested thoroughly and it works for both Geralt and Jaskier in any time scale.
