### ISSUE TITLE
SetCurrentAnimationSpeed() skips part of the animation

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#372]
## Bug Description
Calling the function SetCurrentAnimationSpeed() makes the animation go on a further frame than it currently is, aside from slowing down the animation by the stipulated amount.

Check observations.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [x] Components
* [ ] Game Objects
* [ ] UI/UX 
* [x] Scripting
* [x] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Use SetCurrentAnimationSpeed() on an animation at a very early stage.
 
 2. Use SetCurrentAnimationSpeed() on an animation at a very late stage.
 
 3. Feel free to contact @ch0m5 to get a Scene Setup to test this.

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Animation slows down at the same frame it is asked to.

### Actual result:
Animation slows down but skips a number of frames directly proportional to the amount of frames the animation has already gone through or the time passed since it started.

## Screenshots and Illustrations:
This is shown in a very small TimeScale, but the same behavior occurs with 1.0 TimeScale.
![jaskier_1](https://user-images.githubusercontent.com/36209557/82838891-e4a93480-9ecd-11ea-860d-6ba5d36b7d32.gif)
![jaskier_2](https://user-images.githubusercontent.com/36209557/82838899-ea067f00-9ecd-11ea-9268-1108ab56e7a2.gif)

## Build
0.6.2

## Observations and Additional Information
There seems to be a relationship between how much of the animation has passed and how much of the animation is skipped, since testing shows that slowing down the animation on the most earlier frames doesn't seem to advance the animation much if at all, but the longer the animation has gone for, the more frames it skips when calling the SetCurrentAnimationSpeed() function.

**Comment by Scarzard** [comment]
Pull request #395 fixes this issue
