### ISSUE TITLE
The autocomplete of FindChildGameObjectFromGO is wrong

### ISSUE THREAD

**Issue by DLorenzoLaguno17** [Broken-Gem-Studio/Broken-Engine#385]
## Enhancement Description
It is written FindChidGameObjectFromGO and it should be FindChildGameObjectFromGO instead, it's missing an  L

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [X] UI/UX
* [X] Other

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [X] **Increased Performance**: Optimization which would improve execution performance.
- [ ] **New Feature**: It's an additional feature that fits in the product.
- [X] **Developer Quality of Life Upgrade**: It would optimize current or new implementations.
- [ ] **User Quality of Life Upgrade:** It would improve the User Experience.
- [ ] **Other**: *Describe reason here*

**Comment by lucho1** [comment]
Fixed
