### ISSUE TITLE
Camera FOV is not saved properly

### ISSUE THREAD

**Issue by t3m1X** [Broken-Gem-Studio/Broken-Engine#41]
## Bug Description
When saving the scene the camera's FOV is not saved properly

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [X] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Load a scene with a camera
 
 2. Change the camera's FOV
 
 3. Save the scene

 4. Load the scene

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [X] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
The FOV that you've set is loaded properly

### Actual result:
A random (smaller) FOV is loaded

**Comment by Scarzard** [comment]
ComponentCamera doesn't have a Resource for it

**Comment by AitorSimona** [comment]
No need of resource, components are saved in .scene files. It was a silly placement mistake
