### ISSUE TITLE
Loopable animation makes the head "shake" when restarting animation

### ISSUE THREAD

**Issue by JosepLleal** [Broken-Gem-Studio/Broken-Engine#44]
## Bug Description
Sometimes when an animation with a loop restarts, the head from the character shakes a little bit.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1.  Assign loopable animation to a character
 
 2. Play animation
 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [ ] Always
* [x] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Smooth movement of the head.

### Actual result:
The character's head shakes

## Build
- **Please specify the build:** ``v_0.2``

**Comment by lucho1** [comment]
When you are on it, please make a HacknPlan Task

**Comment by Scarzard** [comment]
It no longer appears to happen
