### ISSUE TITLE
When loading a DynamicRB Component its RB is nullptr

### ISSUE THREAD

**Issue by t3m1X** [Broken-Gem-Studio/Broken-Engine#49]
## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [X] Physics 
* [ ] Audio 
* [ ] Particles
* [X] Resource Management & Save/Load 
* [ ] Materials 
* [X] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [X] Crash 
- [ ] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1.  Save a scene with a dynamicRB
 
 2. Load the scene with dynamicRB, the rigidbody variable seems to be null
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [X] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
The rigidbody is initialized

### Actual result:
Rigidbody appears to be null

## Build
- `v0.2.2`

**Comment by lucho1** [comment]
Había un collider puesto ya?
