### ISSUE TITLE
Lua Script Drag Crash

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#5]
## Bug Description
Engine Crashes when you drag a .lua to it from outside the engine to the Project ImGui window.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Art 
* [ ] Animation 
* [ ] Audio 
* [ ] Particles
* [ ] Stage 
* [ ] Player 
* [ ] Enemies
* [x] UI 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [x] Crash 
- [ ] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Create a .lua file with Notepad or some other file editor.
 
 2. Write something on it and save it as a .lua file.
 
 3. Drag it to the Project window of the engine, it should crash.

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Create a script resource out of the drag & dropped file.

### Actual result:
Crash engine, no resource created.

## Build
https://github.com/Broken-Gem-Studio/TheWitcher/tree/60743dd4380ccc3c2f63a6fe8c89aee887ea2af2

## Observations and Additional Information
Nice first impression - Oveja Obrera

**Comment by DidacRomero** [comment]
This issue was solved by @DLorenzoLaguno17 , now all scripts will be properly imported on dragndrop.
This issue will now be closed.
