### ISSUE TITLE
Having an Active Camera on spams console with one message

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#51]
## Bug Description
Activating a Camera spams one single message over and over on the console, difficulting debugging and being generally annoying.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [x] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1. Create camera GO
 
 2. Set as active camera
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Active Camera is set as ON, maybe just a message on the console marking it

### Actual result:
Console is spammed with the same message over and over.

## Screenshots and Illustrations:
![image](https://user-images.githubusercontent.com/36209557/76399189-81a00b00-637e-11ea-9560-5704b4e9aaf1.png)

## Build
2.0

**Comment by lucho1** [comment]
Should be fixed now
