### ISSUE TITLE
Bug with active cameras

### ISSUE THREAD

**Issue by lucho1** [Broken-Gem-Studio/Broken-Engine#56]
## Bug Description
When creating a camera, if set to active camera, it works, but unsetting it, sets active camera to a nullptr. It might set it to engine camera.

When doing play and then stop with an active camera, since it deactivates the current active camera, happens the same.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [x] Components
* [ ] Game Objects
* [x] UI/UX 
* [x] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1. Create a camera GObj
 
 2. Set it to active
 
 3. Now you can do both thing to reproduce it: Or unsetting the active camera checkbox, or pressing play then stop.

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
To set the active camera to the engine's one

### Actual result:
No camera is setted to active, rendering a complete grey screen (like if there is no active camera and it's only rendering the color buffer cleared to the background color)

## Build
- **Please specify the build:** ``Insert the build here``
0.2.2

**Comment by lucho1** [comment]
I managed to make the active_camera to be the engine's one when unchecking the "Active Camera" checkbox of a camera component, however, the issue happening when pressing stop, has more relation on the scene's load, which doesn't sets an active camera

**Comment by AitorSimona** [comment]
by default when active camera is unchecked the editor camera is assigned, now active camera bool is save & loaded
