### ISSUE TITLE
Scripting Methods for Aard (Geralt's Force Push)

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#57]
## Enhancement Description
I need methods related to physics and collider interaction.

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [ ] Visual 
* [x] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX
* [x] Other

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [ ] **Increased Performance**: Optimization which would improve execution performance.
- [x] **New Feature**: It's an additional feature that fits in the product.
- [ ] **Developer Quality of Life Upgrade**: It would optimize current or new implementations.
- [ ] **User Quality of Life Upgrade:** It would improve the User Experience.
- [ ] **Other**: *Describe reason here*

## Implementation Instructions and Guidelines
As a briefing: Lua can only manage so much data before becoming a complete mess, it simply doesn't have the structure capabilities of C++, so for the sake of simplicity I'd be better to use UIDs to access GameObjects and apply changes to them via Scripting.

1. Collider collecting for enemy detection (return lua table filled with UIDs)
References:
https://docs.unity3d.com/ScriptReference/Physics.OverlapBox.html
https://docs.unity3d.com/ScriptReference/Physics.OverlapSphere.html

2. Apply LinearVelocity to GOs by passing UID
Same as current "SetLinearVelocity", but with the option of passing the GOs UID.

**Comment by DidacRomero** [comment]
@ch0m5 in the next build of the engine you will be able to access other scripts, meaning you can call the method setlinearvelocity from that table of the enemy, apart of accessing all the other variables and functions, does that fulfill your expectations or is there a diferent feature you are trying to convey that could be created as an enhancement.

**Comment by ch0m5** [comment]
> 
> 
> @ch0m5 in the next build of the engine you will be able to access other scripts, meaning you can call the method setlinearvelocity from that table of the enemy, apart of accessing all the other variables and functions, does that fulfill your expectations or is there a diferent feature you are trying to convey that could be created as an enhancement.

I need to access data from the enemy to be able to work with it. I should be able to:

1. Get colliders from a certain area, be it a lua table that contains "collider lua tables" each with data of themselves such as UID of owner GO, or just simple a list of UID of all GOs that have colliders inside the area. Whatever method is used, I need a way to distinguish between colliders/GOs, so stuff like **layers** or **tags** must be created.

2. Be able to get the position of the enemies.

3. Be able to set the velocity of the enemies.

I assume that when you say "you can call the method setlinearvelocity from that table of the enemy" I can call that method and it will be applied to the enemy's GO as the engine will understand that the enemy GO is calling the function.

I do not fully understand the capabilities of being able to access other script tables in the aspect of function calling. I can make myself an idea but I'd need a "tutorial" about it if you don't mind.

**Comment by knela96** [comment]
This can be now implemented with the OverlapSphere, i supose that this Issue can be closed?
