### ISSUE TITLE
Colliders have too many polygons

### ISSUE THREAD

**Issue by Jaumeavinyo** [Broken-Gem-Studio/Broken-Engine#59]
## Enhancement Description
colliders have too many polygons that are not needed

## Type of Enhancement 
* [x ] Components
* [x] Game Objects
* [x] Other

## Why do you propose this enhancement?
- [ x] **Increased Performance**: Optimization which would improve execution performance.

## Implementation Instructions and Guidelines
no

## Observations and Additional Information
Jaume

**Comment by lucho1** [comment]
Colliders have the polygons that are necessary for them to work (cubes 2 per face, capsules the needed ones to make them deform properly...). It's already reviewed.
