### ISSUE TITLE
Debug draw window closes every time you select a debug type

### ISSUE THREAD

**Issue by Jaumeavinyo** [Broken-Gem-Studio/Broken-Engine#60]
## Enhancement Description
The mini window that opens in debug draw should not close when selecting one type of debug draw because maybe want to select more than one. 

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])
* [ x] UI/UX

## Why do you propose this enhancement?
- [x] **User Quality of Life Upgrade:** It would improve the User Experience.

## Implementation Instructions and Guidelines
no

## Observations and Additional Information
jaume

**Comment by DavidTello1** [comment]
solved
