### ISSUE TITLE
Objects have The same name in hierarchy and can't change it

### ISSUE THREAD

**Issue by Jaumeavinyo** [Broken-Gem-Studio/Broken-Engine#61]
## Enhancement Description
When you add for example more than one geralt in the hierarchy, they all have the same name by default. (This is one thing that should change, names should be: Geralt(0), Geralt(1), Geralt(2)...etc
Also cant change the current names in the hierarchy

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [ x] Visual 
* [x ] Game Objects
* [ x] UI/UX

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [x] **User Quality of Life Upgrade:** It would improve the User Experience.
- [x] **Other**: *Describe reason here*
It is something that should be like i describe, i think the work is just incomplete.

## Observations and Additional Information
Jaume

**Comment by AitorSimona** [comment]
You can change a go's name through the inspector. Closing this.
