### ISSUE TITLE
See animation bones when selecting them

### ISSUE THREAD

**Issue by Jaumeavinyo** [Broken-Gem-Studio/Broken-Engine#62]
## Enhancement Description
It would be visualy usefull to be able to see bones when selecting them.  Would help with animation problems

## Type of Enhancement 

* [x] Visual 
* [x] Game Objects
* [x] UI/UX

## Why do you propose this enhancement?

- [x] **New Feature**: It's an additional feature that fits in the product.
- [x] **User Quality of Life Upgrade:** It would improve the User Experience.

## Observations and Additional Information
Jaume

**Comment by Scarzard** [comment]
Not needed
