### ISSUE TITLE
CRASH: Mesh component crashes the engine when click play

### ISSUE THREAD

**Issue by Jaumeavinyo** [Broken-Gem-Studio/Broken-Engine#65]
## Bug Description
Adding a mesh component crashes the engine when click play

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Components
* [x] Game Objects

## Severity

- [x] Crash 

## Reproduction

 1. add game object to the scene
 
 2. add mesh component to the game obj
 
 3. click play

 4. engine crash

## Frequency

* [x] Always

## Screenshots and Illustrations:
not necessary

## Build
- **Please specify the build:** ``Insert the build here``

## Observations and Additional Information
Jaume

**Comment by lucho1** [comment]
Is probable that this should be fixed by not allowing the user to add a mesh renderer

**Comment by JosepLleal** [comment]
Now you can't add a mesh and mesh renderer component to a GO
