### ISSUE TITLE
CRASH: Dinamyc rigid body crash the engine

### ISSUE THREAD

**Issue by Jaumeavinyo** [Broken-Gem-Studio/Broken-Engine#66]
## Bug Description
Dinamyc rigid body component crash the engine

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Components

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [x] Crash 

## Reproduction

 1. add a dynamic rigid body
 
 2. crash
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always

## Build
- **Please specify the build:** ``0.2.3``

## Observations and Additional Information
Jaume

**Comment by lucho1** [comment]
Very similar to issue #49 , gonna close it since it should be fixed with that one already
