### ISSUE TITLE
Component animation should not be by default in objs

### ISSUE THREAD

**Issue by Jaumeavinyo** [Broken-Gem-Studio/Broken-Engine#69]
## Bug Description
Component animation should not be by default in objs, it should be optional to add it

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Components

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [x] Cosmetic 

## Reproduction

 1. add geralt
 
 2. see that there is a default anim component that shouldn't be there
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always

## Build
- **Please specify the build:** ``0.2.3``

## Observations and Additional Information
Jaume

**Comment by lucho1** [comment]
In all the objects you must add a "Component Animation" if you want to, is not setted by default. However, if you import an FBX with animations included, the engine does that automatically.
