### ISSUE TITLE
Open Script File UI doesn't work

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#7]
## Bug Description
Pressing Open Script File doesn't start.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [x] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1. Add a script component to a Game Object.
 
 2. Press Open Script File button.
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Default scripting file opens to edit the file in question.

### Actual result:
Nothing happens.

## Build
https://github.com/Broken-Gem-Studio/TheWitcher/tree/60743dd4380ccc3c2f63a6fe8c89aee887ea2af2

**Comment by DidacRomero** [comment]
This issue was solved with the Hotfix branch, this issue will now be closed, thanks @ch0m5 !
