### ISSUE TITLE
Albedo on mesh renderer stays there forever <3

### ISSUE THREAD

**Issue by Jaumeavinyo** [Broken-Gem-Studio/Broken-Engine#70]
## Bug Description
If you add an albedo on mesh renderer, even if you delete geralt, when you add another geralt and then add a new mesh renderer, the default albedo is not the white albedo that it was the first time you added a mesh renderer, is the last albedo you added. If you add more geralts, all share the same albedo.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Visual 
* [x] Materials 
* [x] Components
* [x] Game Objects

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [x] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1. add geralt to the scene
 
 2. add mesh renderer
 
 3. change the default albedo

 4. delete geralt or not, is not necessary

5. add another geralt to the scene

6. add mesh renderer to the new geralt

7. see that there is the same albedo

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always

## Build
- **Please specify the build:** ``0.2.3``

## Observations and Additional Information
Jaume
cuidado que quizas esto solo pasa para los objetos quye se llaman igual y si en vez de añadir un segundo geralt añades otro obj distinto no comparten el albedo.

**Comment by lucho1** [comment]
Gonna delete this since I think there is a mistake confusing "mesh renderer" by "material". However, materials are shared through objects, so if you change the albedo on one material, an object with the same material will have that albedo too, which is the expected result on materials.
