### ISSUE TITLE
Geralt child objects "Hasta el infinito y más allá"

### ISSUE THREAD

**Issue by Jaumeavinyo** [Broken-Gem-Studio/Broken-Engine#71]
## Bug Description
Geralt child objects fly to the infinite when selecting them separately from their parent and try to translate them

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Game Objects
* [x] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [x] Game stopper/slower

## Reproduction

 1. add geralt
 
 2. select its sword from the scene with mouse picking
 
 3. try moving it

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always

## Build
- **Please specify the build:** ``0.2.3``

## Observations and Additional Information
Jaume

**Comment by lucho1** [comment]
Duplicated. The same than issue #26
