### ISSUE TITLE
Not all components have delete button

### ISSUE THREAD

**Issue by Jaumeavinyo** [Broken-Gem-Studio/Broken-Engine#74]
## Bug Description
Not all components have delete button, some have and some not

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Components

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [x] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1. 
 
 2. 
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [ ] Always

## Build
- **Please specify the build:** ``0.2.3``

## Observations and Additional Information
Jaume

**Comment by lucho1** [comment]
Which ones do and which ones don't? Take into account that some components (mesh renderer, material...) cannot be deleted because they shouldn't.

**Comment by lucho1** [comment]
If this is done, then @Jaumeavinyo, close it and complete please.
