### ISSUE TITLE
Want to change folders and other files names

### ISSUE THREAD

**Issue by Jaumeavinyo** [Broken-Gem-Studio/Broken-Engine#75]
## Enhancement Description
Not able to create a new folder with the name I want for that folder. also cant change any file name

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [x] Visual 
* [x] UI/UX

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [x] **User Quality of Life Upgrade:** It would improve the User Experience.

## Implementation Instructions and Guidelines
if press f2 while a folder is selected or double click in the name, be able to change the name for example.

## Observations and Additional Information
Jaume

**Comment by AitorSimona** [comment]
You can specify a resource name on resource creation. Renaming would require deeper changes, repathing... Given the time left to GOLD, I'm closing this.
