### ISSUE TITLE
Script Editor Values aren't used on the Game Build

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#80]
## Bug Description
Script variable values changed on the Editor aren't used on the Game Build, they use the script's default ones instead.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [x] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [X] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Put the same script on two different GOs
 
 2. Change the values on the editor on each script (different on each)
 
 3. Make a Game Build

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [X] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Game Build uses the script variable values changed on the editor.

### Actual result:
Game Build uses the default script values.

## Build
Since 0.2, or even since the Game Build system was made probably

**Comment by DidacRomero** [comment]
This issue might have been solved whilst attempting to solve another Issue [Save & Load of GOs with Scripts breaks them](https://github.com/Broken-Gem-Studio/Broken-Engine/issues/47), I will proceed to test this issue and if it has been solved by my latest commit I will consider this issue solved and will proceed to close it.

**Comment by DidacRomero** [comment]
Thank you @ch0m5 @t3m1X , the issue was fixed as mentioned in the comment before. This issue will now be closed and it should be working correctly on the next engine Build.
