### ISSUE TITLE
Script Variable Save&Load of Strings doesn't work correctly

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#81]
## Bug Description
The Save&Load system does not save string variables, and instead only seems to saves/loads the first character of the string.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [x] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Use a Script that has a string variable
 
 2. Save&Load the scene with the script
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [X] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
The string is saved and loaded in the variable.

### Actual result:
Only the first character of the string seems to be saved&loaded.

## Build
Since 0.2, or even since the script Save&Load system exists

## Observations and Additional Information
The problem is rooted in the Save/Load of string variables, as if you hardcode the string on the script instead of using variables, the bug ceases to appear.

**Comment by DidacRomero** [comment]
This issue has been resolved! thx @ch0m5 in the next build you should not encounter this problem. This issue will now be closed.
