### ISSUE TITLE
GameObject moving and rotating on it's own (very slowly)

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#86]
## Bug Description
A GameObject seems to be moving and rotating on it's own, very slowly.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [x] Components
* [x] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Go to "TheWitcher\Scene Setups\Geralt_Animations_v3(0.2.5)"
 
 2. Execute that Scene Setup and give Geralt the GeraltScript_v3
 
 3. PLAY

 4. Move around for a while and wait for at least 5-10 minutes.

**Alternative:**

1. Use a script that rotates with LookAt() and moves a GO using physics.

2. When leaving it IDLE, observe if the rotation values change after a while.

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
GO stays still with no changes on position or rotation.

### Actual result:
GO seems to rotate very slowly

## Screenshots and Illustrations:
![image](https://user-images.githubusercontent.com/36209557/76690851-bb099c80-6644-11ea-8c18-9bf41fb18ccb.png)
![Idle_Rotation](https://user-images.githubusercontent.com/36209557/76690929-5995fd80-6645-11ea-98ba-699f7ebab47f.gif)
![image](https://user-images.githubusercontent.com/36209557/76691194-adeeac80-6648-11ea-9dc8-7fa80d7ab407.png)

## Build
0.2.5

## Observations and Additional Information
In the screenshot 1st given, the original angle was 0.0, and in the time of me looking at other stuff when I came back it was a different value. On the 3rd, I pressed PLAY and left it on standby for about 15 minutes without no inputs.

**Comment by lucho1** [comment]
It seems that the problem happens with game objects with colliders and rigid bodies

**Comment by lucho1** [comment]
It also seems to be something appeared with the last big physics fixes, since it happens in v0.2.4, too

**Comment by lucho1** [comment]
Seems in 0.2.3 doesn't happens, and before neither

**Comment by knela96** [comment]
Fixed, the objects rotating. on the scripting it called the setlinearvelocity and in the case those values where 0, it tried to set the velocity having numbers to -0000001 on the movement. Now it works as espected
