### ISSUE TITLE
Null AABB on DrawScene that triggers MathGeoLib's assert (Debug)

### ISSUE THREAD

**Issue by AitorSimona** [Broken-Gem-Studio/Broken-Engine#94]
## Bug Description
When using MathGeoLib's Intersects function with a null aabb, an assert is triggered. Controlled the situation checking first if the aabb is null, but should look into why an aabb is null in the first place.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [X] Game Objects
* [ ] UI/UX 
* [X] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [X] Crash (controlled) 
- [ ] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Get Vertical Slice 1 build assets

 2.  comment aabb.isFinite() condition (check image below)
 
 3. Run on Debug (does not happen in Release)

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [X] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
No assert is triggered, no aabb is null

### Actual result:
aabb is null, assert triggered, engine closes on exception!

## Screenshots and Illustrations:
![Untitled-1](https://user-images.githubusercontent.com/36265599/77004462-6bd2ad00-695f-11ea-93ff-d4596682a29a.png)

## Build
- **Please specify the build:** ``Insert the build here``
Dev branch commit 1175

**Comment by t3m1X** [comment]
Cannot replicate, might be fixed @AitorSimona? If so, please close it.

**Comment by t3m1X** [comment]
Stale issue, closing it
